server:
    port: 8888
    servlet:
        context-path: /simple
#开启展示sql日志
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
    datasource:
        dynamic:
            primary: db1 #设置默认的数据源或者数据源组,默认值即为master
            strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
            datasource:
                db1:
                    driver-class-name: com.mysql.cj.jdbc.Driver
                    url: jdbc:mysql://192.168.22.82:3306/order_db_1?useUnicode=true&useSSL=false
                    username: root
                    password: 123456
                db2:
                    driver-class-name: com.mysql.cj.jdbc.Driver
                    url: jdbc:mysql://192.168.22.82:3306/order_db_2?useUnicode=true&useSSL=false
                    username: root
                    password: 123456
                mydb:
                    driver-class-name: com.mysql.cj.jdbc.Driver
                    url: jdbc:mysql://192.168.22.82:3306/my_db?useUnicode=true&useSSL=false
                    username: root
                    password: 123456
                pgdb:
                    driver-class-name: org.postgresql.Driver
                    url: jdbc:postgresql://192.168.22.82:5432/my_db?useUnicode=true&useSSL=false
                    username: postgres
                    password: 123456
                orcldb:
                    driver-class-name: oracle.jdbc.OracleDriver
                    url: jdbc:oracle:thin:@//192.168.22.82:1521/ORCL
                    username: system
                    password: 123456
